# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Download dependencies
      run: go mod download

    - name: Build
      run: go build -v

    - name: Create logs directory
      run: mkdir logs

    - name: Build test-server
      run: make build-test-server

    - name: Run Tests
      run: go test -v ./...

    - name: Archive logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: logs
        path: |
          logs
